name: Publish VSCode Extension

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Optional: trigger on version tags like v0.2.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Verify version matches Git tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
            echo "Version mismatch: Git tag is $TAG_VERSION but package.json version is $PKG_VERSION"
            exit 1
          fi

      - name: Publish to VSCode Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
        run: vsce publish --pat $VSCE_PAT